### ISSUE TITLE
Design Chatbot Conversation Flows

### ISSUE THREAD

**Issue by adnanbhanji** [adnanbhanji/EU-Chatbot-Reco-System#10]
Develop a conversational schema and dialogue flow for the chatbot, including common queries and responses.

**Comment by smorenolasa1** [comment]
We modified the commands.py to start the registration or report flow based on the user input. For this case, we just modified the code so that when the user sends "start registration" or "start report", the bot will enter the registration/report flow. The bot will track the state of each user to know which part of the flow they are in. For each part of the flow, there is a function that handles the user´s response and asks the next questions. :
![image](https://github.com/adnanbhanji/EU-Chatbot-Reco-System/assets/117740777/4da263db-b172-43e9-bd15-9fa2b40e75e2)

**Comment by smorenolasa1** [comment]
We added a funciton to check if the user wanted to start a report or registration:

**Comment by smorenolasa1** [comment]
These are the funcitons for the chatbot to start asking the questions:
![image](https://github.com/adnanbhanji/EU-Chatbot-Reco-System/assets/117740777/d032c7fe-66b4-4f2a-8241-89529d5692bc)

**Comment by smorenolasa1** [comment]
Our idea involves calling the Chatgpt function if a user's response to a question does not meet our criteria (for example, if the question asks for a numeric answer like 'How many cows do you have?' and the response is not numeric), then ChatGPT will engage with the user to resolve their issue.

Once the issue is resolved and the user provides the correct response to the question, we will store this information for inclusion in our report.

**Comment by riyadmazari** [comment]
We have created a new function to have a conversation flow for the report of the year, continue_report_flow(), we are asking different questions to gain more insight on the farmers report, to be able to store this data and train our recommendation engines on this data. We inspect the input of the user, to check if it is a consistent input. Now the bot is working to start a registration and a report.

**Comment by smorenolasa1** [comment]
Managed to connect chatgpt during the report conversation so that if any doubt arrises, you can ask away. Just type solved when your question was solved, and it will continue asking you the report questions:
![WhatsApp Image 2024-02-21 at 15 50 45](https://github.com/adnanbhanji/EU-Chatbot-Reco-System/assets/117740777/c77cda09-f572-4004-ba1e-9ca115cf764f)
