### ISSUE TITLE
Integrate Chatbot with WhatsApp

### ISSUE THREAD

**Issue by adnanbhanji** [adnanbhanji/EU-Chatbot-Reco-System#11]
Develop the integration layer for the chatbot to function within WhatsApp. This involves setting up communication protocols that allow the chatbot to receive and send messages through WhatsApp, ensuring a seamless user experience as if chatting with a regular contact. The integration should handle user inputs and responses efficiently, maintaining the natural flow of conversation.

Responsible for establishing and maintaining the data pipeline between the chatbot system and WhatsApp's APIs.

**Comment by smorenolasa1** [comment]
We then had to connect to the Flask server to print incoming requests from the sandbox. For this, we use the port 8080 since we used it before to give us the forwarding url. 
Then, to connect to ChatGPT, we had to obtain an OpenAI API Key. We create a config.py to put our vonage accounts(with our sandbox number, and our base encoded credentials, we get from encoding our voice API key and voice API secret), and our openai key.

**Comment by smorenolasa1** [comment]
Then, we had to create a conneciton between ChatGPT and WhatsApp to send and receive the messages. For this we first create an app.py to set up the flask server to print the incoming requests from the sandbox. 
We then create a commands.py(here we have to provide a string value that we got from our sandbox) that receives the message we sent from the sandbox, it then forwards the question, collects the answer, and sends it back to the whatsapp user.

**Comment by smorenolasa1** [comment]
Finally, we run our app.py in the terminal to test that it correctly integrated ChatGPT in Whatsapp. 
Here, we got some errors, since we our openai API quota had exceeded. After fixing this, we could send messages to chatGPT from our whatsapp. 
![image](https://github.com/adnanbhanji/EU-Chatbot-Reco-System/assets/117740777/76c592fc-5abe-4f2a-b43e-4b4d0f52316e)
![image](https://github.com/adnanbhanji/EU-Chatbot-Reco-System/assets/117740777/b5b9ab4f-fa1d-4344-a89c-4925c77519e0)

**Comment by adnanbhanji** [comment]
Perfecrt, we have the communication working between the end user and bot, we now need to finetune it to our CO2 emmision report.

**Comment by KhaledAkel** [comment]
> Perfect, we have the communication working between the end user and bot, we now need to finetune it to our CO2 emmision report.

so we need to tell chatgpt before any new conversation to act like an expert in CO2 emission reports in general. I think that would be the approach.

**Comment by smorenolasa1** [comment]
We fixed the issue with the chatbot not being able to create images:
![image](https://github.com/adnanbhanji/EU-Chatbot-Reco-System/assets/117740777/57bfb6b0-bf16-4637-8ab3-cc1e14bb0adb)
