### ISSUE TITLE
Add conversation flow for Custom Mistral 7B Bot

### ISSUE THREAD

**Issue by adnanbhanji** [adnanbhanji/EU-Chatbot-Reco-System#47]

**Comment by smorenolasa1** [comment]
Managed to get the conversation flow started. Now we have to change the minstral_model_rag.py so that when the conversation flow ends, that it connects to the model:
![image](https://github.com/adnanbhanji/EU-Chatbot-Reco-System/assets/117740777/d44542c1-be81-4c7d-8429-7edfb2824c72)
![image](https://github.com/adnanbhanji/EU-Chatbot-Reco-System/assets/117740777/4c4cb06b-3085-4ce7-b515-c52d3bdf9829)

**Comment by smorenolasa1** [comment]
Now managed to allow the user to continue asking questions to the model´s query engine after the conversation flow had finished:
![image](https://github.com/adnanbhanji/EU-Chatbot-Reco-System/assets/117740777/4e50f402-e41a-42b8-9f93-7618aee80f91)

**Comment by smorenolasa1** [comment]
![image](https://github.com/adnanbhanji/EU-Chatbot-Reco-System/assets/117740777/dcc2ea73-bba8-4dbf-b2bf-ab4e0154be73)
Modified the code to maintain a history of states that the user has visited. Whenever "solved" is entered, the system should use this history to determine the last state and revert to it, allowing the conversation to naturally flow from that point onwards again after your question has been solved.

**Comment by smorenolasa1** [comment]
![image](https://github.com/adnanbhanji/EU-Chatbot-Reco-System/assets/117740777/dcc2ea73-bba8-4dbf-b2bf-ab4e0154be73)
Modified the code to maintain a history of states that the user has visited. Whenever "solved" is entered, the system should use this history to determine the last state and revert to it, allowing the conversation to naturally flow from that point onwards again after your question has been solved.

**Comment by adnanbhanji** [comment]
After testing, conversation flow working fine, and generating pdf. 
Issue Closed.
